spring:
  application:
    name: product-service
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN}
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: ecommerce
        application-name: product-service
  config:
    import: optional:vault://
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
      auto-offset-reset: latest
application:
  kafka:
    group-id:
      product-service.product.update-quantity: product-service.product.update-quantity
    topics:
      inventory-service.product.update: inventory-service.product.update
      product-service.product.update-quantity: product-service.product.update-quantity
server:
  servlet:
    context-path: /product-service